baseURL = 'https://myasuka.org/'
defaultContentLanguage = 'zh-cn'
title = 'Above the Abstraction'
theme = 'hextra'

[taxonomies]
  tag = "tags"
  category = "categories"

[services]
  [services.googleAnalytics]
    ID = "G-MTW2ZB8K4E"

[languages]
  [languages.zh-cn]
    languageName = "中文"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

[params]
  [params.navbar]
    displayTitle = true
    displayLogo = true
    [params.navbar.logo]
      path = "images/avatar.png"
      dark = "images/avatar.png"
      link = "/"
      width = 24
      height = 24

[params.footer]
  displayCopyright = true
  displayPoweredBy = true

[params.search]
  enable = true

[params.comments]
  enable = true
  type = "giscus"
  [params.comments.giscus]
    repo = "myasuka/myasuka.github.io"
    repoId = "MDEwOlJlcG9zaXRvcnk2MTU2NDQxMA=="
    category = "General"
    categoryId = "DIC_kwDOA6tl-s4CvZsn"
    mapping = "pathname"
    theme = "preferred_color_scheme"
    lang = "zh-CN"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pageRef = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Search"
    weight = 4
    params = { type = "search" }
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/myasuka/myasuka.github.io"
    weight = 5
    params = { icon = "github" }
  [[menu.main]]
    name = "Language Switcher"
    weight = 6
    params = { type = "language-switch", label = true, icon = "globe-alt" }

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
